"""Native type-1 scene-light definitions and runtime transfer fields.

Retail serializer ``0x14109A9D0`` writes the fixed fields below in order.
Runtime conversion ``0x14109A1F0`` selects light-type behavior from byte
``+0x92`` and copies the RGB triplet at ``+0xA0``.  The type-1 dispatcher at
``0x14109AF50`` supplies the remaining direct runtime fields.  The semantic
names below are pinned by that copy, native ``LightDef`` reflection, and the
frame-record consumers that feed the 128-byte ``LightGpu`` packer.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
import struct


SCENE_LIGHT_TYPE = 1
SCENE_LIGHT_MINIMUM_SIZE = 0xF0
SCENE_LIGHT_SCALAR_OFFSETS = tuple(range(0xBC, 0xF0, 4))
SCENE_LIGHT_ATTENUATION_RADIUS_FLOOR = 0.009999999776482582
SCENE_LIGHT_AUTO_RADIUS_COLOR_WEIGHTS = (
    1.7007999420166016,
    5.72160005569458,
    0.5776000022888184,
)
SCENE_LIGHT_CONE_INNER_LIMIT = 0.9900000095367432

# Double-precision constants used by retail's scalar trigonometric helpers at
# 0x141639AE0 and 0x14163A200. The helpers reduce a float32 angle to a triangle
# wave, evaluate this odd polynomial in float64, then round once to float32.
_NATIVE_TRIG_COEFFICIENTS = tuple(float.fromhex(value) for value in (
    '0x1.921fb520817f7p+0',
    '-0x1.4abbc16acf9cdp-1',
    '0x1.4668af65619a5p-4',
    '-0x1.324cc645b6d0ep-8',
    '0x1.3daf748a890afp-13',
))
_NATIVE_TRIG_INVERSE_TWO_PI = float.fromhex('0x1.45f306dc9c883p-3')

# (serialized offset, semantic name, direct runtime offset).  Attenuation is
# conditional and clamped; the other entries are copied bit-for-bit before
# the native type-1 initializer derives cone and culling data.
SCENE_LIGHT_TYPE1_SCALAR_FIELDS = (
    (0xBC, 'intensity', 0xA0),
    (0xC0, 'attenuation_radius', 0x120),
    (0xC4, 'cutoff_radius', 0x12C),
    (0xC8, 'cut_on_distance', 0x130),
    (0xCC, 'specular_intensity', 0xC8),
    (0xD0, 'specular_fade_out_distance', 0xCC),
    (0xD4, 'fade_out_distance', 0xC4),
    (0xD8, 'inner_cone', 0x124),
    (0xDC, 'outer_cone', 0x128),
    (0xE0, 'bulb_radius', 0x138),
    (0xE4, 'bulb_length', 0x13C),
    (0xE8, 'shadow_cut_on_distance', 0x134),
    (0xEC, 'bulb_push_forward', 0x140),
)


@dataclass(frozen=True)
class SceneLightDefinition:
    """Exact cooked fields of one native type-1 scene node."""

    matrix: tuple[float, ...]
    node_flags: int
    scale: tuple[float, float, float]
    serialized_size: int
    field_80: int
    toggle_bits: int
    option_bits: int
    light_type: int
    field_93: int
    field_94: int
    field_95: int
    trailing_string_offset: int
    field_98: int
    field_9c: int
    color: tuple[float, float, float]
    packed_pair_ac: tuple[int, int]
    field_b0: float
    field_b4: int
    field_b8: int
    scalar_values: tuple[float, ...]
    trailing_string: str | None

    @property
    def position(self) -> tuple[float, float, float]:
        return self.matrix[12:15]

    def scalar_at(self, offset: int) -> float:
        """Return one still-unnamed scalar by its serialized byte offset."""

        try:
            index = SCENE_LIGHT_SCALAR_OFFSETS.index(int(offset))
        except ValueError as error:
            raise ValueError(
                'Scene-light scalar offset must be aligned in 0xBC..0xEC') from error
        return self.scalar_values[index]

    @property
    def volumetric_fog_intensity(self) -> float:
        """Return the value transferred through runtime ``+0xB4``."""

        return self.field_b0

    def type_1_runtime_transfer(self) -> 'SceneLightType1RuntimeTransfer':
        """Build the exact direct-copy portion of native type-1 conversion."""

        return build_scene_light_type_1_runtime_transfer(self)

    def local_basis_transform(
            self) -> tuple[tuple[float, float, float, float], ...]:
        """Resolve the serialized matrix through retail's local-basis helper."""

        return build_scene_light_local_basis_transform(self.matrix)


@dataclass(frozen=True)
class SceneLightType1RuntimeTransfer:
    """Direct fields present immediately before type-1 derived initialization.

    ``attenuation_radius_override`` is ``None`` when serialized ``+0xC0`` is
    not positive.  In that case retail preserves the radius generated by the
    type initializer instead of writing an override.
    """

    color: tuple[float, float, float]
    volumetric_fog_intensity: float
    intensity: float
    attenuation_radius_override: float | None
    cutoff_radius: float
    cut_on_distance: float
    specular_intensity: float
    specular_fade_out_distance: float
    fade_out_distance: float
    inner_cone: float
    outer_cone: float
    bulb_radius: float
    bulb_length: float
    shadow_cut_on_distance: float
    bulb_push_forward: float
    runtime_flags: int

    def runtime_float_fields(self) -> tuple[tuple[int, float], ...]:
        """Return the direct runtime float writes in ascending offset order."""

        fields = [
            (0xA0, self.intensity),
            (0xA8, self.color[0]),
            (0xAC, self.color[1]),
            (0xB0, self.color[2]),
            (0xB4, self.volumetric_fog_intensity),
            (0xC4, self.fade_out_distance),
            (0xC8, self.specular_intensity),
            (0xCC, self.specular_fade_out_distance),
            (0x124, self.inner_cone),
            (0x128, self.outer_cone),
            (0x12C, self.cutoff_radius),
            (0x130, self.cut_on_distance),
            (0x134, self.shadow_cut_on_distance),
            (0x138, self.bulb_radius),
            (0x13C, self.bulb_length),
            (0x140, self.bulb_push_forward),
        ]
        if self.attenuation_radius_override is not None:
            fields.append((0x120, self.attenuation_radius_override))
        return tuple(sorted(fields))

    def derived_runtime(self) -> 'SceneLightType1DerivedRuntime':
        """Apply retail's second type-1 derived-initializer pass."""

        return build_scene_light_type_1_derived_runtime(self)


@dataclass(frozen=True)
class SceneLightType1DerivedRuntime:
    """Scalar writes and culling inputs produced by ``0x14109CD80``.

    The native routine forwards ``culling_center_and_radius`` and
    ``culling_half_extents`` to the manager's bounds helper. Resolving and
    committing the scene transform happens later at ``0x1412B6370``.
    ``cone_scale`` and ``cone_bias`` retain the previous runtime values when
    both cone angles are zero, represented here by ``None``.
    """

    attenuation_radius: float
    cone_scale: float | None
    cone_bias: float | None
    cone_culling_length: float
    cut_on_distance: float
    shadow_cut_on_distance: float
    culling_half_extents: tuple[float, float, float]
    culling_center_and_radius: tuple[float, float, float, float]

    def runtime_float_fields(self) -> tuple[tuple[int, float], ...]:
        """Return the derived runtime writes before the bounds-helper call."""

        fields = [
            (0x120, self.attenuation_radius),
            (0x130, self.cut_on_distance),
            (0x134, self.shadow_cut_on_distance),
            (0x14C, self.cone_culling_length),
        ]
        if self.cone_scale is not None:
            fields.extend(((0x144, self.cone_scale), (0x148, self.cone_bias)))
        return tuple(sorted(fields))


@dataclass(frozen=True)
class SceneLightResolvedTransform:
    """Runtime transform commit produced by ``0x1412B6370``.

    Classification is computed from the incoming float4 rows before retail
    overwrites their homogeneous components with ``(0, 0, 0, 1)``. Only the
    low five bits of ``transform_flags`` belong to this classification.
    """

    matrix: tuple[tuple[float, float, float, float], ...]
    axis_scales: tuple[float, float, float]
    transform_flags: int


def _float32(value: float) -> float:
    """Round one scalar through IEEE-754 binary32."""

    return struct.unpack('<f', struct.pack('<f', float(value)))[0]


def _float32_add(left: float, right: float) -> float:
    return _float32(_float32(left) + _float32(right))


def _float32_subtract(left: float, right: float) -> float:
    return _float32(_float32(left) - _float32(right))


def _float32_multiply(left: float, right: float) -> float:
    return _float32(_float32(left) * _float32(right))


def _float32_divide(left: float, right: float) -> float:
    numerator = _float32(left)
    denominator = _float32(right)
    if denominator == 0.0:
        if numerator == 0.0:
            return math.nan
        negative = math.copysign(1.0, numerator) != math.copysign(
            1.0, denominator)
        return -math.inf if negative else math.inf
    return _float32(numerator / denominator)


def _native_trig_polynomial(angle: float, phase_cycles: float) -> float:
    """Reproduce the scalar cosine polynomial with an optional cycle phase."""

    source = _float32(angle)
    if not math.isfinite(source):
        raise ValueError('Scene-light cone angles must be finite float32 values')
    scaled = float(source) * _NATIVE_TRIG_INVERSE_TWO_PI
    scaled -= phase_cycles
    fraction = scaled - math.floor(scaled)
    cycle = fraction * 4.0
    normalized = 1.0 - cycle if 2.0 - cycle >= 0.0 else cycle - 3.0
    c0, c1, c2, c3, c4 = _NATIVE_TRIG_COEFFICIENTS

    term_2 = c2 * normalized
    term_3 = c3 * normalized
    square = normalized * normalized
    term_1 = c1 * normalized
    term_3 *= square
    fourth = square * square
    term_1 *= square
    term_3 += term_2
    term_0 = c0 * normalized
    term_3 *= fourth
    term_1 += term_0
    eighth = fourth * fourth
    term_4 = c4 * normalized
    term_4 *= eighth
    result = term_3 + term_1
    result += term_4
    return _float32(result)


def _native_cosine(angle: float) -> float:
    return _native_trig_polynomial(angle, 0.0)


def _native_sine(angle: float) -> float:
    return _native_trig_polynomial(angle, 0.25)


def _scene_light_matrix_rows(matrix):
    """Round either a flat or row-shaped scene matrix to finite binary32."""

    try:
        values = tuple(matrix)
        if len(values) == 16 and not any(
                isinstance(value, (tuple, list)) for value in values):
            rows = tuple(tuple(
                _float32(values[row * 4 + column]) for column in range(4)
            ) for row in range(4))
        else:
            rows = tuple(tuple(_float32(value) for value in row)
                         for row in values)
    except (TypeError, ValueError, OverflowError) as error:
        raise ValueError('Scene-light transform must be a float4x4') from error
    if len(rows) != 4 or any(len(row) != 4 for row in rows):
        raise ValueError('Scene-light transform must be a float4x4')
    if not all(math.isfinite(value) for row in rows for value in row):
        raise ValueError('Scene-light transform must be finite')
    return rows


def _native_stable_normalize3(vector, fallback):
    """Normalize one float3 with the overflow-safe scalar path at 0x1402BD1A0."""

    x, y, z = (_float32(value) for value in vector)
    maximum = max(abs(z), abs(y), abs(x))
    if maximum <= 0.0:
        return tuple(_float32(value) for value in fallback)
    scale = _float32_divide(1.0, maximum)
    scaled_x = _float32_multiply(scale, x)
    scaled_y = _float32_multiply(scale, y)
    scaled_z = _float32_multiply(scale, z)
    squared = _float32_add(
        _float32_multiply(scaled_y, scaled_y),
        _float32_multiply(scaled_x, scaled_x))
    squared = _float32_add(
        squared, _float32_multiply(scaled_z, scaled_z))
    inverse_length = _float32_divide(
        1.0, _float32(math.sqrt(max(squared, 0.0))))
    return (
        _float32_multiply(inverse_length, scaled_x),
        _float32_multiply(inverse_length, scaled_y),
        _float32_multiply(inverse_length, scaled_z),
    )


def _native_dot3(left, right) -> float:
    """Use the y+x+z accumulation order in the retail basis helper."""

    value = _float32_add(
        _float32_multiply(left[1], right[1]),
        _float32_multiply(left[0], right[0]))
    return _float32_add(value, _float32_multiply(left[2], right[2]))


def _native_cross3(left, right):
    return (
        _float32_subtract(
            _float32_multiply(left[1], right[2]),
            _float32_multiply(left[2], right[1])),
        _float32_subtract(
            _float32_multiply(left[2], right[0]),
            _float32_multiply(left[0], right[2])),
        _float32_subtract(
            _float32_multiply(left[0], right[1]),
            _float32_multiply(left[1], right[0])),
    )


def _native_orient_like(vector, reference):
    if _native_dot3(vector, reference) < 0.0:
        return tuple(_float32(-value) for value in vector)
    return vector


def build_scene_light_local_basis_transform(matrix):
    """Reproduce source-matrix basis resolution at ``0x1402BD1A0``.

    Retail derives the first axis from ``cross(row1, row2)``, preserves the
    direction of row 0, derives the third axis from ``cross(axis0, row1)``,
    preserves the direction of row 2, and independently normalizes row 1.
    Degenerate axes use the native identity-axis fallbacks. Serialized scale
    and shear therefore do not pass this boundary; translation is retained.
    """

    rows = _scene_light_matrix_rows(matrix)
    row_0, row_1, row_2, translation = rows
    axis_0 = _native_stable_normalize3(
        _native_cross3(row_1[:3], row_2[:3]), (1.0, 0.0, 0.0))
    axis_0 = _native_orient_like(axis_0, row_0[:3])
    axis_2 = _native_stable_normalize3(
        _native_cross3(axis_0, row_1[:3]), (0.0, 0.0, 1.0))
    axis_2 = _native_orient_like(axis_2, row_2[:3])
    axis_1 = _native_stable_normalize3(
        row_1[:3], (0.0, 1.0, 0.0))
    return (
        (*axis_0, 0.0),
        (*axis_1, 0.0),
        (*axis_2, 0.0),
        (translation[0], translation[1], translation[2], 1.0),
    )


def select_scene_light_owner_transform(
        owner_transform=None, runtime_fallback_transform=None, *,
        already_world: bool = False, embedded_transform=None,
        use_embedded_override: bool = False):
    """Select the owner-space matrix returned by ``0x140FE5C30``.

    Runtime flag ``+0x4C & 0x01000000`` selects the embedded matrix at
    ``+0x60`` first. Otherwise owner flag ``+0xC6`` selects the runtime
    fallback, while a clear flag dereferences the ``+0x10`` holder and uses
    that matrix when non-null. The fallback value is supplied explicitly
    because retail address ``0x146838510`` is runtime-backed rather than
    present in the executable file.
    """

    if use_embedded_override:
        if embedded_transform is None:
            raise ValueError(
                'Embedded scene-light owner transform is required when '
                'the runtime override is enabled')
        return _scene_light_matrix_rows(embedded_transform)
    if already_world or owner_transform is None:
        if runtime_fallback_transform is None:
            raise ValueError(
                'Runtime fallback transform is required for scene-light '
                'owner resolution')
        return _scene_light_matrix_rows(runtime_fallback_transform)
    return _scene_light_matrix_rows(owner_transform)


def compose_scene_light_owner_transform(
        record_transform, owner_transform=None, *, already_world: bool = False):
    """Apply the external owner transform used by scene-light placement.

    The placement path at ``0x140FEEE07`` installs the cooked record first,
    then either keeps its raw transform when ``already_world`` is true or
    multiplies ``record_transform * owner_transform`` through
    ``0x141627F80``. Matrices use the retail row-vector convention. The
    paired multiply/add order below mirrors that helper's SIMD instruction
    order so every component is rounded to binary32 at the same boundaries.
    Pass the result to :func:`build_scene_light_resolved_transform` to model
    the subsequent commit at ``0x1412B6BF0``.
    """

    record_rows = _scene_light_matrix_rows(record_transform)
    if already_world:
        return record_rows
    if owner_transform is None:
        raise ValueError(
            'Scene-light owner transform is required unless already_world')
    owner_rows = _scene_light_matrix_rows(owner_transform)
    result = []
    for row in record_rows:
        output_row = []
        for column in range(4):
            owner_0 = owner_rows[0][column]
            owner_1 = owner_rows[1][column]
            owner_2 = owner_rows[2][column]
            owner_3 = owner_rows[3][column]
            high = _float32_add(
                _float32_multiply(row[3], owner_3),
                _float32_multiply(row[1], owner_1))
            low = _float32_add(
                _float32_multiply(row[2], owner_2),
                _float32_multiply(row[0], owner_0))
            output_row.append(_float32_add(high, low))
        result.append(tuple(output_row))
    return tuple(result)

def build_scene_light_resolved_transform(
        matrix, *, existing_transform_flags: int = 0,
        ) -> SceneLightResolvedTransform:
    """Reproduce matrix analysis/commit at ``0x141629E60``/``0x1412B6370``."""

    rows = _scene_light_matrix_rows(matrix)
    flags = int(existing_transform_flags)
    if not 0 <= flags <= 0xffffffff:
        raise ValueError('Existing scene-light transform flags must fit uint32')

    a, b, c = rows[:3]
    determinant = _float32_multiply(a[2], b[0])
    determinant = _float32_multiply(determinant, c[1])
    term = _float32_multiply(b[2], a[1])
    term = _float32_multiply(term, c[0])
    positive = _float32_multiply(b[1], a[0])
    positive = _float32_multiply(positive, c[2])
    positive = _float32_add(positive, term)
    positive = _float32_add(positive, determinant)
    term = _float32_multiply(b[2], a[0])
    term = _float32_multiply(term, c[1])
    determinant = _float32_subtract(positive, term)
    term = _float32_multiply(b[0], a[1])
    term = _float32_multiply(term, c[2])
    determinant = _float32_subtract(determinant, term)
    term = _float32_multiply(b[1], a[2])
    term = _float32_multiply(term, c[0])
    determinant = _float32_subtract(determinant, term)
    classification = 4 if determinant < 0.0 else 0

    squared_scales = []
    for row in rows[:3]:
        first = _float32_add(
            _float32_multiply(row[1], row[1]),
            _float32_multiply(row[0], row[0]))
        second = _float32_add(
            _float32_multiply(row[3], row[3]),
            _float32_multiply(row[2], row[2]))
        squared_scales.append(_float32_add(second, first))
    scale_0, scale_1, scale_2 = squared_scales
    maximum = max(scale_1, scale_0, scale_2)
    minimum = min(scale_1, scale_0, scale_2)
    spread = _float32(abs(_float32_subtract(maximum, minimum)))
    tolerance = _float32_multiply(minimum, .01)
    if spread >= tolerance:
        classification |= 1 << 4

    middle = _float32_subtract(
        _float32_subtract(
            _float32_add(_float32_add(scale_1, scale_0), scale_2), minimum),
        maximum)
    if scale_0 == middle:
        median_axis = 0
    elif scale_1 == middle:
        median_axis = 1
    else:
        median_axis = 2
    classification |= median_axis
    axis_scales = tuple(
        _float32(math.sqrt(max(value, 0.0))) for value in squared_scales)
    committed = (
        (a[0], a[1], a[2], 0.0),
        (b[0], b[1], b[2], 0.0),
        (c[0], c[1], c[2], 0.0),
        (rows[3][0], rows[3][1], rows[3][2], 1.0),
    )
    return SceneLightResolvedTransform(
        matrix=committed,
        axis_scales=axis_scales,
        transform_flags=(flags & ~0x1f) | classification,
    )


def build_scene_light_type_1_derived_runtime(
        transfer: SceneLightType1RuntimeTransfer,
        ) -> SceneLightType1DerivedRuntime:
    """Reproduce retail type-1 scalar derivation at ``0x14109CD80``.

    Cooked scene definitions always enter this second pass with native flag
    bit 16 clear, so attenuation radius is derived from the copied RGB value.
    The returned culling vectors are the exact local inputs passed to
    ``0x1412B6AA0`` immediately before the resolved transform is committed.
    """

    if not isinstance(transfer, SceneLightType1RuntimeTransfer):
        raise ValueError('transfer must be SceneLightType1RuntimeTransfer')
    values = (
        *transfer.color,
        transfer.cutoff_radius,
        transfer.cut_on_distance,
        transfer.shadow_cut_on_distance,
        transfer.inner_cone,
        transfer.outer_cone,
    )
    if not all(math.isfinite(_float32(value)) for value in values):
        raise ValueError('Scene-light derived inputs must be finite float32 values')
    if transfer.runtime_flags & (1 << 16):
        if transfer.attenuation_radius_override is None:
            raise ValueError(
                'Native flag bit 16 requires an existing attenuation radius')
        attenuation_radius = _float32(transfer.attenuation_radius_override)
    else:
        red = _float32_multiply(
            transfer.color[0], SCENE_LIGHT_AUTO_RADIUS_COLOR_WEIGHTS[0])
        green = _float32_multiply(
            transfer.color[1], SCENE_LIGHT_AUTO_RADIUS_COLOR_WEIGHTS[1])
        blue = _float32_multiply(
            transfer.color[2], SCENE_LIGHT_AUTO_RADIUS_COLOR_WEIGHTS[2])
        weighted = _float32_add(green, red)
        weighted = _float32_add(weighted, blue)
        attenuation_radius = _float32(math.sqrt(max(weighted, 0.0)))

    inner = _float32(transfer.inner_cone)
    outer = _float32(transfer.outer_cone)
    cone_scale = None
    cone_bias = None
    if inner != 0.0 or outer != 0.0:
        limited_outer = _float32_multiply(
            outer, SCENE_LIGHT_CONE_INNER_LIMIT)
        limited_inner = min(max(inner, 0.0), limited_outer)
        cosine_inner = _native_cosine(limited_inner)
        cosine_outer = _native_cosine(outer)
        cone_scale = _float32_divide(
            1.0, _float32_subtract(cosine_inner, cosine_outer))
        cone_bias = _float32(-_float32_multiply(cone_scale, cosine_outer))

    cosine_outer = _native_cosine(outer)
    sine_outer = _native_sine(outer)
    axial = _float32_multiply(attenuation_radius, cosine_outer)
    radial = _float32_multiply(attenuation_radius, sine_outer)
    cone_culling_length = attenuation_radius
    effective_radius = attenuation_radius
    cutoff = _float32(transfer.cutoff_radius)
    if cutoff > 0.0:
        if cutoff < axial:
            axial = cutoff
            cone_culling_length = _float32_divide(cutoff, cosine_outer)
            radial = _float32_multiply(cone_culling_length, sine_outer)
        effective_radius = min(cutoff, attenuation_radius)

    maximum_cut_on = max(_float32_subtract(
        effective_radius, SCENE_LIGHT_ATTENUATION_RADIUS_FLOOR), 0.0)
    cut_on = min(_float32(transfer.cut_on_distance), maximum_cut_on)
    shadow_cut_on = max(
        _float32(transfer.shadow_cut_on_distance), cut_on)
    shadow_cut_on = min(shadow_cut_on, maximum_cut_on)
    shadow_cut_on = max(
        shadow_cut_on, SCENE_LIGHT_ATTENUATION_RADIUS_FLOOR)

    midpoint = _float32_multiply(
        _float32_add(cut_on, effective_radius), 0.5)
    axial_offset = _float32_subtract(axial, midpoint)
    half_length = _float32_subtract(effective_radius, midpoint)
    radial_squared = _float32_multiply(radial, radial)
    axial_squared = _float32_multiply(axial_offset, axial_offset)
    bound_squared = _float32_add(axial_squared, radial_squared)
    bounding_radius = _float32(math.sqrt(max(bound_squared, 0.0)))
    return SceneLightType1DerivedRuntime(
        attenuation_radius=attenuation_radius,
        cone_scale=cone_scale,
        cone_bias=cone_bias,
        cone_culling_length=cone_culling_length,
        cut_on_distance=cut_on,
        shadow_cut_on_distance=shadow_cut_on,
        culling_half_extents=(radial, radial, half_length),
        culling_center_and_radius=(0.0, 0.0, midpoint, bounding_radius),
    )


def build_scene_light_type_1_runtime_transfer(
        definition: SceneLightDefinition) -> SceneLightType1RuntimeTransfer:
    """Reproduce retail's direct cooked-record to type-1 runtime transfer."""

    if definition.light_type != 1:
        raise ValueError(
            f'Expected native light type 1, found {definition.light_type}')

    values = {
        name: definition.scalar_at(offset)
        for offset, name, _runtime_offset in SCENE_LIGHT_TYPE1_SCALAR_FIELDS
    }
    attenuation = values['attenuation_radius']
    attenuation_override = (
        max(attenuation, SCENE_LIGHT_ATTENUATION_RADIUS_FLOOR)
        if attenuation > 0.0 else None
    )

    # The common converter starts from the zero-extended 16-bit option word.
    flags = definition.option_bits
    if values['intensity'] > 0.0:
        flags |= 1 << 18
    else:
        flags &= ~(1 << 18)

    # UCOMISS/JNE treats both zero and unordered values as the zero branch.
    specular = values['specular_intensity']
    if specular == 0.0 or specular != specular:
        flags = (flags & ~2) | 1
    if values['specular_fade_out_distance'] > 0.0 and not flags & 3:
        flags |= 1 << 20
    if values['fade_out_distance'] > 0.0:
        flags |= 1 << 21
    if attenuation > 0.0:
        flags |= 1 << 22

    return SceneLightType1RuntimeTransfer(
        color=definition.color,
        volumetric_fog_intensity=definition.field_b0,
        intensity=values['intensity'],
        attenuation_radius_override=attenuation_override,
        cutoff_radius=values['cutoff_radius'],
        cut_on_distance=values['cut_on_distance'],
        specular_intensity=specular,
        specular_fade_out_distance=values['specular_fade_out_distance'],
        fade_out_distance=values['fade_out_distance'],
        inner_cone=values['inner_cone'],
        outer_cone=values['outer_cone'],
        bulb_radius=values['bulb_radius'],
        bulb_length=values['bulb_length'],
        shadow_cut_on_distance=values['shadow_cut_on_distance'],
        bulb_push_forward=values['bulb_push_forward'],
        runtime_flags=flags,
    )


def _relative_string(raw: memoryview, offset: int) -> str | None:
    if offset == 0:
        return None
    if not SCENE_LIGHT_MINIMUM_SIZE <= offset < raw.nbytes:
        raise ValueError('Scene-light trailing string offset is outside its record')
    tail = raw[offset:].tobytes()
    terminator = tail.find(b'\0')
    if terminator < 0:
        raise ValueError('Scene-light trailing string is not null terminated')
    return tail[:terminator].decode('utf-8', errors='replace')


def parse_scene_light_definition(
        data: bytes | bytearray | memoryview) -> SceneLightDefinition:
    """Parse exactly one cooked native type-1 light definition.

    The serialized-size field at ``+0x7C`` controls the record boundary.  Its
    high bit is masked consistently with the shared scene-node loader.
    """

    raw = memoryview(data)
    if raw.nbytes < 0x80:
        raise ValueError('Scene-light definition is shorter than its header')
    node_type = raw[0x5F]
    if node_type != SCENE_LIGHT_TYPE:
        raise ValueError(f'Expected scene node type 1, found {node_type}')
    serialized_size = struct.unpack_from('<I', raw, 0x7C)[0] & 0x7FFFFFFF
    if serialized_size < SCENE_LIGHT_MINIMUM_SIZE:
        raise ValueError(
            f'Scene-light definition is shorter than 0x{SCENE_LIGHT_MINIMUM_SIZE:X} bytes')
    if serialized_size != raw.nbytes:
        raise ValueError(
            'Scene-light input must contain exactly one serialized definition')

    return SceneLightDefinition(
        matrix=struct.unpack_from('<16f', raw, 0),
        node_flags=struct.unpack_from('<I', raw, 0x5C)[0],
        scale=struct.unpack_from('<3f', raw, 0x70),
        serialized_size=serialized_size,
        field_80=struct.unpack_from('<Q', raw, 0x80)[0],
        toggle_bits=struct.unpack_from('<Q', raw, 0x88)[0],
        option_bits=struct.unpack_from('<H', raw, 0x90)[0],
        light_type=raw[0x92],
        field_93=raw[0x93],
        field_94=raw[0x94],
        field_95=raw[0x95],
        trailing_string_offset=struct.unpack_from('<H', raw, 0x96)[0],
        field_98=struct.unpack_from('<I', raw, 0x98)[0],
        field_9c=struct.unpack_from('<I', raw, 0x9C)[0],
        color=struct.unpack_from('<3f', raw, 0xA0),
        packed_pair_ac=struct.unpack_from('<2H', raw, 0xAC),
        field_b0=struct.unpack_from('<f', raw, 0xB0)[0],
        field_b4=struct.unpack_from('<I', raw, 0xB4)[0],
        field_b8=struct.unpack_from('<I', raw, 0xB8)[0],
        scalar_values=struct.unpack_from('<13f', raw, 0xBC),
        trailing_string=_relative_string(raw, struct.unpack_from('<H', raw, 0x96)[0]),
    )
