"""Translate verified Forge direct-hair equations for a controlled UE diagnostic."""
import hashlib
import json
from pathlib import Path
import re
from export_recovered_core import hlsl

root=Path(__file__).resolve().parents[2]
core=root/'external/RCRA-Forge/core'
names=['fur_gbuffer.glsl','hair_frame.glsl','hair_lobes.glsl','hair_response.glsl','hair_environment_frame.glsl']
def translate(source):
    source=hlsl(source)
    for before,after in [('uvec2','uint2'),('uvec3','uint3'),('uvec4','uint4'),('inversesqrt','rsqrt')]:
        source=re.sub(r'\b'+before+r'\b',after,source)
    # HLSL casts splat scalar arguments and preserve same-sized vector casts.
    pattern=re.compile(r'\b(float[234]|uint[234])\(')
    matches=list(pattern.finditer(source))
    for m in reversed(matches):
        start=m.end();level=1;end=start;commas=0
        while level:
            c=source[end]
            if c=='(':level+=1
            elif c==')':level-=1
            elif c==',' and level==1:commas+=1
            end+=1
        if commas==0:
            source=source[:m.start()]+'(('+m[1]+')('+source[start:end-1]+'))'+source[end:]
    return re.sub(r'\blinear\b','linearTerm',source)

sources={name:(core/name).read_text() for name in names}
shader='// Generated by export_reference_lighting.py. Recovered direct and authored-cube response.\n#ifndef RF_REFERENCE_LIGHTING\n#define RF_REFERENCE_LIGHTING\n'
shader+='\n'.join(translate(s) for s in sources.values())
shader+='''
float RFDirectDistribution(HairLobeFrame frame, float3 strand, float3 light,
                          float3 view, float3 halfVector, float2 alpha)
{
    return hairLobeDistribution(float3(dot(frame.normal,halfVector),dot(strand,halfVector),dot(frame.side,halfVector)),
        alpha,saturate(dot(frame.normal,light)),min(abs(dot(frame.normal,view))+0.00001,1.0));
}
float3 RFSceneDirect(float3 normal, float3 strand, float3 view, float3 light,
                        float4 albedoOcclusion, float2 glossSpecular, float viewDepthM, float transmittance)
{
    uint4 packed=furPackGBuffer(normal,glossSpecular.x,glossSpecular.y,0u);
    uint extra=furPackExtra(strand,transmittance);
    normal=furUnpackNormal(packed);
    strand=furUnpackStrand(extra);
    HairMaterialResponse material=hairMaterialResponse(packed,extra,albedoOcclusion,viewDepthM);
    float3 secondaryStrand=hairSecondaryStrand(strand,normal,extra>>26u);
    HairLobeFrame primary=hairLobeFrame(strand,normal,view);
    HairLobeFrame secondary=hairLobeFrame(secondaryStrand,normal,view);
    float3 halfVector=normalize(light+view);
    float primaryDistribution=RFDirectDistribution(primary,strand,light,view,halfVector,material.primaryAlpha);
    float secondaryDistribution=RFDirectDistribution(secondary,secondaryStrand,light,view,halfVector,material.secondaryAlpha);
    float3 primarySpecular=hairFresnel(material.primaryF0,dot(view,halfVector))*primaryDistribution;
    float3 secondarySpecular=hairFresnel(material.secondaryF0,dot(view,halfVector))*secondaryDistribution;
    float normalLight=dot(normal,light),normalView=dot(normal,view);
    float diffuse=hairDiffuseResponse(normalLight,material.transmission);
    float back=hairTransmissionResponse(dot(-view,hairWrappedLight(normal,light)),normalLight,normalView);
    float3 weights=hairResolveWeights(material.transmission,normalView,material.occlusion,1.0);
    return hairResolveLighting(albedoOcclusion.rgb,material.occlusion,0.0,weights,
                              diffuse+secondarySpecular,back.xxx,primarySpecular,float3(0,0,0));
}
// Optional scene fill/rim contributions use the same recovered response as key.
// A zero radiance returns before normalization/lobe evaluation, preserving old
// single-light behavior and avoiding invalid vectors for disconnected lights.
float3 RFSceneAdditionalDirect(float3 normal,float3 strand,float3 view,
    float3 direction,float3 radiance,float4 albedoOcclusion,float2 glossSpecular,
    float viewDepthM,float transmittance)
{
    if (!any(radiance > 0) || dot(direction,direction) < 1e-8)
        return float3(0,0,0);
    return RFSceneDirect(normal,strand,view,normalize(direction),albedoOcclusion,
        glossSpecular,viewDepthM,transmittance)*max(radiance,0);
}
// Authored prefiltered cube bridge. Cube directions use UE axes by default;
// recoveredAxes=1 is for private Forge-oriented cube comparisons.
float3 RFSceneEnvironment(TextureCube cube,SamplerState cubeSampler,
    Texture2D brdf,SamplerState brdfSampler,float3 normal,float3 strand,float3 view,
    float4 albedoOcclusion,float2 glossSpecular,float viewDepthM,float transmittance,
    float angle,float intensity,float maxMip,float recoveredAxes)
{
    if(intensity<=0) return float3(0,0,0);
    uint4 packed=furPackGBuffer(normal,glossSpecular.x,glossSpecular.y,0u);
    uint extra=furPackExtra(strand,transmittance);
    normal=furUnpackNormal(packed);strand=furUnpackStrand(extra);
    HairMaterialResponse material=hairMaterialResponse(packed,extra,albedoOcclusion,viewDepthM);
    HairLobeFrame primary=hairLobeFrame(strand,normal,view);
    HairEnvironmentFrame env=hairEnvironmentFrame(normal,strand,view,primary,
        material.primaryAlpha,material.gloss,angle);
    float3 reflection=recoveredAxes>.5 ? env.reflection : env.reflection.xzy;
    float3 diffuseDirection=recoveredAxes>.5 ? normal : normal.xzy;
    float3 specularLight=cube.SampleLevel(cubeSampler,reflection,
        max(maxMip,0)*(1-saturate(env.averageGloss))).rgb*intensity;
    float3 diffuseLight=cube.SampleLevel(cubeSampler,diffuseDirection,max(maxMip,0)).rgb*intensity;
    float2 lookup=brdf.SampleLevel(brdfSampler,
        float2(saturate(abs(dot(env.normal,view))),saturate(env.averageGloss)),0).rg;
    float3 indirectSpecular=specularLight*(material.primaryF0*lookup.x+lookup.y);
    float3 indirectDiffuse=diffuseLight+specularLight*material.secondaryF0;
    float3 weights=hairResolveWeights(material.transmission,dot(normal,view),material.occlusion,1);
    return hairResolveLighting(albedoOcclusion.rgb,material.occlusion,0,weights,
        indirectDiffuse,float3(0,0,0),indirectSpecular,float3(0,0,0));
}
float3 RFReferenceDirect(float3 normal,float3 strand,float3 view,float3 light,
    float4 albedoOcclusion,float2 glossSpecular,float viewDepthM)
{
    return RFSceneDirect(normal,strand,view,light,albedoOcclusion,glossSpecular,viewDepthM,.1);
}
#endif
'''
target=root/'unreal/plugins/FurAuthoring/Shaders/ReferenceHairLighting.ush'
target.write_text(shader)
out=root/'unreal/fur/matched-reference'
(out/'lighting-provenance.json').write_text(json.dumps({'sources':{n:hashlib.sha256(s.encode()).hexdigest() for n,s in sources.items()},
    'hlsl_sha256':hashlib.sha256(shader.encode()).hexdigest(),
    'limits':['Direct key and authored prefiltered-cube bridge only','No captured MRT rounding, contact depth, scene probe selection or temporal resolve',
              'HLSL mad is not established as bit-identical to native fused rounding']},indent=2))
(out/'lighting-compile.hlsl').write_text('#include "../../plugins/FurAuthoring/Shaders/ReferenceHairLighting.ush"\nfloat4 main(float4 p:SV_Position):SV_Target { return float4(RFReferenceDirect(float3(0,1,0),normalize(float3(.2,1,.1)),normalize(float3(1,1,1)),normalize(float3(.6,1,.8)),float4(.3,.2,.1,1),float2(.4,.5),1),1); }')
print(target)
