"""Rebuild portable fur kernels and lossless DDS array from this Forge checkout.

No renderer is started. Older outer-workspace layouts remain supported so the
historical validation commands recorded in CHECKPOINT.md stay reproducible.
"""
import ast
import hashlib
import json
from pathlib import Path
import re
import struct
import numpy as np

ROOT = Path(__file__).resolve().parents[2]
FORGE = ROOT if (ROOT / 'ui/viewport.py').is_file() else ROOT / 'external/RCRA-Forge'
PLUGIN = ROOT / 'unreal/plugins/FurAuthoring'
OUT = ROOT / 'unreal/fur/recovered'


def sha(data):
    return hashlib.sha256(data).hexdigest()


def hlsl(source):
    # Select the precise GLSL branch, retaining operation order. HLSL mad is
    # not a guarantee of native D3D12 fused rounding: GPU parity is separate.
    source = re.sub(r'#ifdef GL_ARB_gpu_shader5\n(.*?)#else\n.*?#endif',
                    lambda m: m[1], source, flags=re.S)
    for before, after in [('vec2', 'float2'), ('vec3', 'float3'), ('vec4', 'float4'),
                          ('uintBitsToFloat', 'asfloat'), ('fract', 'frac'), ('fma', 'mad')]:
        source = re.sub(r'\b' + before + r'\b', after, source)
    # GLSL scalar vector constructors splat; HLSL requires explicit components.
    source = source.replace('float4(wetBlend)', 'wetBlend.xxxx')
    source = source.replace('float2(inversePrevious)', 'inversePrevious.xx')
    return source


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    viewport_path = FORGE / 'ui/viewport.py'
    viewport = viewport_path.read_text(encoding='utf-8')
    tree = ast.parse(viewport)
    names = {'_build_fur_layer_volume', '_build_fur_layer_mips'}
    functions = [n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name in names]
    assert len(functions) == 2
    scope = {'np': np}
    exec(compile(ast.Module(body=functions, type_ignores=[]), str(viewport_path), 'exec'), scope)
    mips = scope['_build_fur_layer_mips']()
    assert [list(m.shape) for m in mips] == [[32, n, n] for n in (128, 64, 32, 16)]
    # DX10 DDS: R8_UNORM, Texture2D array, all four authored mips.
    header = [124, 0x2100F, 128, 128, 128, 0, 4] + [0] * 11
    header += [32, 4, int.from_bytes(b'DX10', 'little'), 0, 0, 0, 0, 0]
    header += [0x401008, 0, 0, 0, 0]
    assert len(header) == 31
    payload = b''.join(mip[s].tobytes() for s in range(32) for mip in mips)
    dds = b'DDS ' + struct.pack('<31I', *header) + struct.pack('<5I', 61, 3, 0, 32, 0) + payload
    (OUT / 'DefaultFurShells.dds').write_bytes(dds)
    # Independent DDS layout readback checks slice order and mip offsets.
    offset = 148
    for s in range(32):
        for mip in mips:
            size = mip.shape[1] * mip.shape[2]
            assert dds[offset:offset + size] == mip[s].tobytes()
            offset += size
    assert offset == len(dds)

    material_path = FORGE / 'core/fur_material.glsl'
    noise_path = FORGE / 'core/hair_lighting_noise.glsl'
    material = hlsl(material_path.read_text())
    noise = hlsl(noise_path.read_text())
    start = viewport.index('const vec4 RETAIL_WIND_RANDOM[64]')
    end = viewport.index('\nfloat pointWrappedControlLength', start)
    wind = hlsl(viewport[start:end])
    wind = wind.replace('const float4 RETAIL_WIND_RANDOM[64] = float4[64](',
                        'static const float4 RETAIL_WIND_RANDOM[64] = {')
    wind = wind.replace('\n);', '\n};', 1)
    wind = wind.replace('float windTime) {', 'float windTime, float turbulence, float objectPhase, float radius, float strength) {')
    for before, after in [('uFurWindTurbulence', 'turbulence'), ('uFurWindObjectPhase', 'objectPhase'),
                          ('uFurWindRadius', 'radius'), ('uFurWindStrength', 'strength')]:
        wind = wind.replace(before, after)
    shader = ('// Generated by unreal/fur/export_recovered_core.py; do not edit.\n'
              '// Ported equations; HLSL fusion and host raster/lighting parity are not established.\n'
              '#ifndef FUR_RECOVERED_CORE_USH\n#define FUR_RECOVERED_CORE_USH\n'
              + material + '\n' + noise + '\n' + wind + '\n#endif\n')
    target = PLUGIN / 'Shaders/RecoveredFurCore.ush'
    target.write_text(shader, encoding='utf-8')
    report = {
        'source_sha256': {str(p.relative_to(ROOT)): sha(p.read_bytes()) for p in
                          (viewport_path, material_path, noise_path)},
        'shader_sha256': sha(target.read_bytes()),
        'dds_sha256': sha(dds), 'dds_bytes': len(dds),
        'mips': [{'shape': list(m.shape), 'sha256': sha(m.tobytes())} for m in mips],
        'dds_slice_mip_readback': 'passed',
        'scope': 'Exact procedural bytes and translated equations; no claim of full renderer parity.'
    }
    (OUT / 'provenance.json').write_text(json.dumps(report, indent=2) + '\n')
    print(json.dumps(report, indent=2))


if __name__ == '__main__':
    main()
